kind: ReplicaSet
apiVersion: apps/v1
metadata:
  name: my-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    containers:
      - name: my-container
        image: nginx:latest
        ports:
          - containerPort: 80
    metadata:
      labels:
        app: my-app