kind: Deployment
apiVersion: apps/v1
metadata:
  name: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: mohamed710/webapp:latest
          ports:
            - containerPort: 80